"use client";

import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type Locale = "en" | "pt";
type LanguageContextValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (english: string) => string };
const LanguageContext = createContext<LanguageContextValue>({ locale: "en", setLocale: () => undefined, t: (value) => value });
const storageKey = "ap-language";
const textOrigins = new WeakMap<Text, { en: string; pt: string }>();
const attributeOrigins = new WeakMap<Element, Map<string, { en: string; pt: string }>>();

const portuguese: Record<string, string> = {
  "Dashboard": "Painel", "New match": "Novo jogo", "Reports": "Relatórios", "Maintenance": "Manutenção", "Settings": "Definições", "Back": "Voltar", "Sign out": "Terminar sessão",
  "Tactics, local video and moments": "Tática, vídeo e momentos", "Matches": "Jogos", "Match reports": "Relatórios de jogos", "Aggregated analysis": "Análise agregada",
  "Select matches, find clips, then play or export the results.": "Selecione jogos, encontre clips e reproduza ou exporte os resultados.",
  "Filter by analysed team": "Filtrar por equipa analisada", "All analysed teams": "Todas as equipas analisadas", "Start date": "Data inicial", "End date": "Data final", "Select visible": "Selecionar visíveis", "Clear selection": "Limpar seleção", "Clear dates": "Limpar datas",
  "Moment": "Momento", "All moments": "Todos os momentos", "Submoment": "Submomento", "All submoments": "Todos os submomentos", "Export quality": "Qualidade de exportação",
  "Select all clips": "Selecionar todos", "Clear clips": "Limpar clips", "Play all": "Reproduzir todos", "Full match videos": "Vídeos completos", "Matches ordered by date.": "Jogos ordenados por data.", "Match": "Jogo", "Date": "Data", "Video": "Vídeo", "Download": "Descarregar", "Export": "Exportar", "Unavailable": "Indisponível", "Copy link": "Copiar link",
  "Matches ordered by date. Export burns the scoreboard into the video; copy link sends the original full match.": "Jogos ordenados por data. Exportar grava o placar no vídeo; copiar link envia o jogo completo original.", "Undo score": "Anular resultado", "Increase score": "Aumentar resultado", "Decrease score": "Diminuir resultado",
  "Configuration": "Configuração", "Manage seasons, competitions and their participating clubs.": "Gerir épocas, competições e clubes participantes.", "Seasons": "Épocas", "Clubs / teams": "Clubes / equipas", "Competitions": "Competições", "Name": "Nome", "Short name": "Nome curto", "Club logo": "Logótipo do clube", "Choose image": "Escolher imagem", "Remove": "Remover", "Season": "Época", "Participating clubs": "Clubes participantes", "Save": "Guardar", "Add": "Adicionar", "Cancel": "Cancelar", "Edit": "Editar", "Delete": "Eliminar",
  "Video analysis": "Análise de vídeo", "Analysing:": "A analisar:", "Tagged moments": "Momentos marcados", "Export all": "Exportar todos", "Export MP4 clip": "Exportar clip MP4", "Completed moments appear here.": "Os momentos concluídos aparecem aqui.", "Upload the match video": "Carregar o vídeo do jogo", "Expected video": "Vídeo esperado", "Upload new": "Carregar novo", "Cloud library": "Biblioteca cloud", "Replace video": "Substituir vídeo", "Upload video": "Carregar vídeo", "Identify submoments": "Identificar submomentos", "Match periods": "Períodos do jogo", "Set": "Definir", "Go": "Ir", "Second": "Segundo",
  "Manage submoment buttons": "Gerir botões de submomentos", "Add submoment": "Adicionar submomento", "Edit submoment type": "Editar tipo de submomento", "Submoment name": "Nome do submomento", "Code": "Código", "Code (automatic)": "Código (automático)", "Saved": "Guardados", "Clips": "Clips", "Select a clip.": "Selecione um clip.",
  "Offensive Organization": "Organização ofensiva", "Defensive Organization": "Organização defensiva", "Offensive Transition": "Transição ofensiva", "Defensive Transition": "Transição defensiva", "Set Pieces": "Bolas paradas",
  "Kickoff": "Pontapé de saída", "Goalkeeper Build-up": "Construção do guarda-redes", "Build-up": "Construção", "Chance Creation": "Criação de oportunidades", "Right Channel": "Corredor direito", "Left Channel": "Corredor esquerdo", "Finishing": "Finalização", "Goal": "Golo", "High Block": "Bloco alto", "Mid Block": "Bloco médio", "Low Block": "Bloco baixo",
  "Original": "Original", "High quality": "Alta qualidade", "Standard": "Padrão", "Loading…": "A carregar…", "Loading clips…": "A carregar clips…", "Exporting…": "A exportar…", "Close": "Fechar", "Pause": "Pausa", "Play": "Reproduzir", "Mute video": "Desligar som", "Enable video sound": "Ligar som",
};

Object.assign(portuguese, {
  "3–32 characters. Letters, numbers, dots, underscores and hyphens.": "3–32 caracteres. Letras, números, pontos, underscores e hífenes.",
  "A network error interrupted the video upload.": "Um erro de rede interrompeu o carregamento do vídeo.",
  "A submoment with this code already exists.": "Já existe um submomento com este código.",
  "A video part could not be uploaded.": "Não foi possível carregar uma parte do vídeo.",
  "Account sign-in password": "Palavra-passe de início de sessão",
  "Active tag cancelled.": "Marcação ativa cancelada.",
  "Add missing videos": "Adicionar vídeos em falta",
  "Adjust shortcuts, main types and submoments. These settings can grow without changing the local video workflow.": "Ajuste atalhos, tipos principais e submomentos. Estas definições podem crescer sem alterar o fluxo de vídeo local.",
  "All of this type": "Todos deste tipo",
  "Already have an account?": "Já tem uma conta?",
  "Also mark the zone on the goal.": "Marque também a zona na baliza.",
  "Analyse": "Analisar",
  "Analyse as opponent": "Analisar como adversário",
  "Analysis hub": "Centro de análise",
  "Analysis perspective": "Perspetiva da análise",
  "Analysis settings": "Definições da análise",
  "Area and global passwords": "Palavras-passe por área e global",
  "Area or global password": "Palavra-passe da área ou global",
  "At least 8 characters, with uppercase, lowercase and a number.": "Pelo menos 8 caracteres, com maiúscula, minúscula e um número.",
  "Away team": "Equipa visitante",
  "Back 15 seconds": "Recuar 15 segundos",
  "Back 5 seconds": "Recuar 5 segundos",
  "Back 5 seconds (left arrow)": "Recuar 5 segundos (seta esquerda)",
  "Back to area access": "Voltar ao acesso da área",
  "Change": "Alterar",
  "Checking access...": "A verificar acesso...",
  "Choose a valid image.": "Escolha uma imagem válida.",
  "Choose an existing video": "Escolher um vídeo existente",
  "Choose the team to analyse": "Escolher a equipa a analisar",
  "Choose the team to analyse.": "Escolha a equipa a analisar.",
  "Choose the team you want to analyse first.": "Escolha primeiro a equipa que pretende analisar.",
  "Choose the team you want to study as the opponent. The same saved moments will automatically be shown from that team's perspective.": "Escolha a equipa que pretende estudar como adversário. Os mesmos momentos guardados serão apresentados automaticamente na perspetiva dessa equipa.",
  "Click a shortcut and press the new key.": "Clique num atalho e prima a nova tecla.",
  "Click on the field": "Clique no campo",
  "Click on the goal": "Clique na baliza",
  "Click to start": "Clique para iniciar",
  "Clip opened. Mark the submoment at the right time.": "Clip aberto. Marque o submomento no instante correto.",
  "Clip position": "Posição do clip",
  "Close cloud library": "Fechar biblioteca cloud",
  "Close message": "Fechar mensagem",
  "Cloudflare did not return the ETag for an uploaded part. Check the bucket CORS policy.": "A Cloudflare não devolveu o ETag de uma parte carregada. Verifique a política CORS do bucket.",
  "Cloudflare R2 did not return a multipart upload ID.": "A Cloudflare R2 não devolveu um identificador para o carregamento multipartes.",
  "Club logo preview": "Pré-visualização do logótipo do clube",
  "Complete or select a moment on the left to identify submoments.": "Conclua ou selecione um momento à esquerda para identificar submomentos.",
  "Confirm": "Confirmar",
  "Confirm global password": "Confirmar palavra-passe global",
  "Confirm password": "Confirmar palavra-passe",
  "Confirm the account password and choose a new global password.": "Confirme a palavra-passe da conta e escolha uma nova palavra-passe global.",
  "Confirm the link. Both applications will then use the same library permanently.": "Confirme a ligação. Ambas as aplicações passarão a usar permanentemente a mesma biblioteca.",
  "Connect another application": "Ligar outra aplicação",
  "Connect the Player, Team and Opponent applications to one private video library. The files are shared without uploading or duplicating them again.": "Ligue as aplicações de Jogador, Equipa e Adversário a uma única biblioteca privada de vídeos. Os ficheiros são partilhados sem novo carregamento ou duplicação.",
  "Connected applications:": "Aplicações ligadas:",
  "Copy": "Copiar",
  "Correct type and clip times": "Corrigir tipo e tempos do clip",
  "Could not connect to the server. Please try again.": "Não foi possível ligar ao servidor. Tente novamente.",
  "Could not export the video with the new engine.": "Não foi possível exportar o vídeo com o novo motor.",
  "Could not load the cloud library": "Não foi possível carregar a biblioteca cloud",
  "Could not open local storage.": "Não foi possível abrir o armazenamento local.",
  "Could not play this video. For better compatibility, use MP4 with H.264 codec.": "Não foi possível reproduzir este vídeo. Para melhor compatibilidade, utilize MP4 com codec H.264.",
  "Could not prepare the logo.": "Não foi possível preparar o logótipo.",
  "Could not prepare the scoreboard overlay.": "Não foi possível preparar o placar.",
  "Could not prepare the video for export.": "Não foi possível preparar o vídeo para exportação.",
  "Could not read the logo.": "Não foi possível ler o logótipo.",
  "Could not read the selected video.": "Não foi possível ler o vídeo selecionado.",
  "Could not record the clip.": "Não foi possível gravar o clip.",
  "Could not restore the local video.": "Não foi possível restaurar o vídeo local.",
  "Could not save the video in the browser.": "Não foi possível guardar o vídeo no navegador.",
  "Create": "Criar",
  "Create account": "Criar conta",
  "Create linking code": "Criar código de ligação",
  "Create match": "Criar jogo",
  "Create new match": "Criar novo jogo",
  "Create one": "Criar um",
  "Create the clubs first.": "Crie primeiro os clubes.",
  "Create the first match to start tagging organization, transition and set-piece moments.": "Crie o primeiro jogo para começar a marcar momentos de organização, transição e bolas paradas.",
  "Create your private workspace. Your matches, analyses and videos will only be available in your account.": "Crie o seu espaço privado. Os seus jogos, análises e vídeos só estarão disponíveis na sua conta.",
  "Creating account...": "A criar conta...",
  "Duration": "Duração",
  "Duration:": "Duração:",
  "Each area has its own password. The global password unlocks the entire application.": "Cada área tem a sua própria palavra-passe. A palavra-passe global desbloqueia toda a aplicação.",
  "Edit analysis": "Editar análise",
  "Edit clip": "Editar clip",
  "Edit match": "Editar jogo",
  "Edit moment": "Editar momento",
  "Edit submoment": "Editar submomento",
  "Edit submoments": "Editar submomentos",
  "End": "Fim",
  "End 1st half": "Fim da 1.ª parte",
  "End 2nd half": "Fim da 2.ª parte",
  "Enter a valid cloud library linking code.": "Introduza um código válido de ligação à biblioteca cloud.",
  "Enter a valid time in seconds.": "Introduza um tempo válido em segundos.",
  "Exact second": "Segundo exato",
  "Exit fullscreen": "Sair do ecrã inteiro",
  "Expected:": "Esperado:",
  "Export all registered moments": "Exportar todos os momentos registados",
  "Export clip": "Exportar clip",
  "Exporting": "A exportar",
  "Field": "Campo",
  "First half": "Primeira parte",
  "For security, change your temporary password before continuing.": "Por segurança, altere a palavra-passe temporária antes de continuar.",
  "Forgot the global password?": "Esqueceu-se da palavra-passe global?",
  "Forward 15 seconds": "Avançar 15 segundos",
  "Forward 5 seconds": "Avançar 5 segundos",
  "Forward 5 seconds (right arrow)": "Avançar 5 segundos (seta direita)",
  "Full match export requires a recent version of Chrome or Edge.": "A exportação do jogo completo requer uma versão recente do Chrome ou Edge.",
  "Fullscreen video and moments": "Vídeo e momentos em ecrã inteiro",
  "Generated automatically from the name and linked to this moment.": "Gerado automaticamente a partir do nome e associado a este momento.",
  "Global": "Global",
  "Global password": "Palavra-passe global",
  "Go to latest tag": "Ir para a última marcação",
  "Go to start": "Ir para o início",
  "Go to this submoment": "Ir para este submomento",
  "Go to time": "Ir para o tempo",
  "Home team": "Equipa da casa",
  "Horizontal football pitch": "Campo de futebol horizontal",
  "How to connect two applications": "Como ligar duas aplicações",
  "In progress": "Em curso",
  "Incorrect area or global password.": "Palavra-passe da área ou global incorreta.",
  "Incorrect global password.": "Palavra-passe global incorreta.",
  "Incorrect sign-in password.": "Palavra-passe de início de sessão incorreta.",
  "Install": "Instalar",
  "Install app": "Instalar aplicação",
  "Interactive goal": "Baliza interativa",
  "Invalid access action.": "Ação de acesso inválida.",
  "Invalid access area.": "Área de acesso inválida.",
  "Invalid analysis perspective.": "Perspetiva de análise inválida.",
  "Invalid clip order.": "Ordem dos clips inválida.",
  "Invalid club logo.": "Logótipo do clube inválido.",
  "Invalid or expired session.": "Sessão inválida ou expirada.",
  "Invalid score or video time.": "Resultado ou tempo do vídeo inválido.",
  "Invalid season, competition or teams.": "Época, competição ou equipas inválidas.",
  "Invalid submoment order.": "Ordem dos submomentos inválida.",
  "Language": "Idioma",
  "Link": "Ligar",
  "Link this application": "Ligar esta aplicação",
  "Linked": "Ligada",
  "Loading cloud videos…": "A carregar vídeos da cloud…",
  "Loading the cloud video…": "A carregar vídeo da cloud…",
  "Local video storage is not available in this browser.": "O armazenamento local de vídeo não está disponível neste navegador.",
  "Main moments": "Momentos principais",
  "Mark": "Marcar",
  "Mark as negative": "Marcar como negativo",
  "Mark as positive": "Marcar como positivo",
  "Mark submoment": "Marcar submomento",
  "Mark the area": "Marcar a zona",
  "Mark the current video time, then use the saved button to jump to it.": "Marque o tempo atual do vídeo e utilize depois o botão guardado para ir até esse instante.",
  "Mark the field zone first.": "Marque primeiro a zona do campo.",
  "Mark the target": "Marcar o alvo",
  "Match not found.": "Jogo não encontrado.",
  "Match or moment type not found.": "Jogo ou tipo de momento não encontrado.",
  "Matches and opponents": "Jogos e adversários",
  "MEDIA_R2_ENDPOINT must use HTTPS.": "MEDIA_R2_ENDPOINT tem de utilizar HTTPS.",
  "Missing MEDIA_LIBRARY_APP_ID.": "MEDIA_LIBRARY_APP_ID em falta.",
  "Moment deleted successfully.": "Momento eliminado com sucesso.",
  "Moment deleted.": "Momento eliminado.",
  "Moment details": "Detalhes do momento",
  "Moment not found.": "Momento não encontrado.",
  "Moment or submoment type not found.": "Momento ou tipo de submomento não encontrado.",
  "Moment position": "Posição do momento",
  "Moment type not found.": "Tipo de momento não encontrado.",
  "Moment updated successfully.": "Momento atualizado com sucesso.",
  "Moment updated.": "Momento atualizado.",
  "Moments": "Momentos",
  "Negative": "Negativo",
  "New analysis": "Nova análise",
  "New global password": "Nova palavra-passe global",
  "New password": "Nova palavra-passe",
  "New submoment": "Novo submomento",
  "New type": "Novo tipo",
  "No analyses yet": "Ainda não existem análises",
  "No associated options are available. Check the Maintenance area.": "Não existem opções associadas. Verifique a área de Manutenção.",
  "No matches in the selected date range.": "Não existem jogos no intervalo de datas selecionado.",
  "No moments registered.": "Não existem momentos registados.",
  "No shared videos yet": "Ainda não existem vídeos partilhados",
  "No submoments are configured for this moment.": "Não existem submomentos configurados para este momento.",
  "No submoments configured for this moment.": "Não existem submomentos configurados para este momento.",
  "No video has been associated with this match yet.": "Ainda não foi associado nenhum vídeo a este jogo.",
  "None of the selected videos are available in this browser.": "Nenhum dos vídeos selecionados está disponível neste navegador.",
  "Note": "Nota",
  "Notes": "Notas",
  "One or more submoments were not found.": "Um ou mais submomentos não foram encontrados.",
  "Only submoments in the same group can be reordered.": "Só é possível reordenar submomentos do mesmo grupo.",
  "Only videos belonging to this account are shown. Selecting one does not upload another copy.": "Só são apresentados vídeos pertencentes a esta conta. Selecionar um não carrega outra cópia.",
  "Open analysis": "Abrir análise",
  "Open cloud library": "Abrir biblioteca cloud",
  "Open the other application and paste the code under “Link this application”.": "Abra a outra aplicação e cole o código em «Ligar esta aplicação».",
  "Opponent analysis": "Análise do adversário",
  "Opponent context, observations or analysis goals": "Contexto do adversário, observações ou objetivos da análise",
  "Optional time": "Tempo opcional",
  "Organization, transitions, set pieces and results are shown in the reversed perspective.": "A organização, transições, bolas paradas e resultados são apresentados na perspetiva invertida.",
  "Password": "Palavra-passe",
  "Paste linking code": "Colar código de ligação",
  "PNG, JPG or WebP. The image is resized automatically.": "PNG, JPG ou WebP. A imagem é redimensionada automaticamente.",
  "Positive": "Positivo",
  "Prepare": "Preparar",
  "Press...": "Prima...",
  "Preview": "Pré-visualizar",
  "Protected area": "Área protegida",
  "Quick logging": "Registo rápido",
  "R2_ENDPOINT must use HTTPS.": "R2_ENDPOINT tem de utilizar HTTPS.",
  "Remove clip from export": "Remover clip da exportação",
  "Replace with current time": "Substituir pelo tempo atual",
  "Reset and unlock all": "Repor e desbloquear tudo",
  "Reset the global password": "Repor a palavra-passe global",
  "Result classification": "Classificação do resultado",
  "Resume analysis": "Retomar análise",
  "Review": "Rever",
  "Save and open analysis": "Guardar e abrir análise",
  "Save changes": "Guardar alterações",
  "Save password": "Guardar palavra-passe",
  "Save submoment": "Guardar submomento",
  "Save type": "Guardar tipo",
  "Saving": "A guardar",
  "Saving...": "A guardar...",
  "Saving…": "A guardar…",
  "Score change not found.": "Alteração do resultado não encontrada.",
  "Search by team, opponent or title": "Pesquisar por equipa, adversário ou título",
  "Search matches": "Pesquisar jogos",
  "Season, competition and teams are required.": "A época, competição e equipas são obrigatórias.",
  "Select a finishing submoment first.": "Selecione primeiro um submomento de finalização.",
  "Select a moment to log submoments.": "Selecione um momento para registar submomentos.",
  "Select a submoment first.": "Selecione primeiro um submomento.",
  "Select a submoment in the list to jump to its timestamp.": "Selecione um submomento na lista para ir até ao respetivo instante.",
  "Select at least one saved analysis to display clips.": "Selecione pelo menos uma análise guardada para apresentar clips.",
  "Select clip for export": "Selecionar clip para exportação",
  "Select multiple videos": "Selecionar vários vídeos",
  "Select the local match video first.": "Selecione primeiro o vídeo local do jogo.",
  "Select video": "Selecionar vídeo",
  "Select…": "Selecionar…",
  "Set a new password": "Definir uma nova palavra-passe",
  "Shared cloud library": "Biblioteca cloud partilhada",
  "Shared Cloudflare R2 did not return a multipart upload ID.": "A Cloudflare R2 partilhada não devolveu um identificador para o carregamento multipartes.",
  "Shortcut": "Atalho",
  "Shortcut not found.": "Atalho não encontrado.",
  "Shortcut saved.": "Atalho guardado.",
  "Shortcuts": "Atalhos",
  "Show clip export options": "Mostrar opções de exportação do clip",
  "Sign in": "Iniciar sessão",
  "Signing in...": "A iniciar sessão...",
  "Start": "Início",
  "Start 1st half": "Início da 1.ª parte",
  "Start 2nd half": "Início da 2.ª parte",
  "Stay here": "Ficar aqui",
  "Submoment deleted.": "Submomento eliminado.",
  "Submoment not found.": "Submomento não encontrado.",
  "Submoment position in the clip": "Posição do submomento no clip",
  "Submoment saved.": "Submomento guardado.",
  "Submoment type not found.": "Tipo de submomento não encontrado.",
  "Submoment updated.": "Submomento atualizado.",
  "Submoments": "Submomentos",
  "The action starts automatically as soon as all videos are available.": "A ação começa automaticamente assim que todos os vídeos estiverem disponíveis.",
  "The browser does not have enough space to save the video.": "O navegador não tem espaço suficiente para guardar o vídeo.",
  "The clip is outside the selected video duration.": "O clip está fora da duração do vídeo selecionado.",
  "The clips must belong to the same moment group.": "Os clips têm de pertencer ao mesmo grupo de momentos.",
  "The cloud video is not available. Select the local video to continue.": "O vídeo da cloud não está disponível. Selecione o vídeo local para continuar.",
  "The code is private, expires after 30 minutes and works once. The permanent link does not share account passwords.": "O código é privado, expira após 30 minutos e só funciona uma vez. A ligação permanente não partilha palavras-passe da conta.",
  "The completed cloud video size does not match the selected file.": "O tamanho do vídeo concluído na cloud não corresponde ao ficheiro selecionado.",
  "The direct cut finished without video data.": "O corte direto terminou sem dados de vídeo.",
  "The end time must be after the start time.": "O tempo final tem de ser posterior ao tempo inicial.",
  "The export file path is empty.": "O caminho do ficheiro de exportação está vazio.",
  "The export finished without video data.": "A exportação terminou sem dados de vídeo.",
  "The full match export finished without video data.": "A exportação do jogo completo terminou sem dados de vídeo.",
  "The home and away teams must be different.": "As equipas da casa e visitante têm de ser diferentes.",
  "The main moments have been saved. You can now continue to submoment identification.": "Os momentos principais foram guardados. Pode agora continuar para a identificação de submomentos.",
  "The moment position is invalid.": "A posição do momento é inválida.",
  "The new passwords do not match.": "As novas palavras-passe não coincidem.",
  "The other team is created automatically as a second perspective. Both share the same video and moments.": "A outra equipa é criada automaticamente como segunda perspetiva. Ambas partilham o mesmo vídeo e os mesmos momentos.",
  "The password must contain at least 4 characters.": "A palavra-passe tem de conter pelo menos 4 caracteres.",
  "The passwords do not match.": "As palavras-passe não coincidem.",
  "The round and both teams are required.": "A jornada e ambas as equipas são obrigatórias.",
  "The second team is not configured for this match.": "A segunda equipa não está configurada para este jogo.",
  "The selected competition or teams do not belong to this season.": "A competição ou equipas selecionadas não pertencem a esta época.",
  "The selected file does not appear to be a video. Use MP4/H.264 for better compatibility.": "O ficheiro selecionado não parece ser um vídeo. Utilize MP4/H.264 para melhor compatibilidade.",
  "The selected file does not contain a video track.": "O ficheiro selecionado não contém uma faixa de vídeo.",
  "The selected video format is not supported by the fast exporter.": "O formato de vídeo selecionado não é suportado pelo exportador rápido.",
  "The selected video has an invalid duration.": "O vídeo selecionado tem uma duração inválida.",
  "The server did not start the multipart upload.": "O servidor não iniciou o carregamento multipartes.",
  "The signed-in user no longer exists.": "O utilizador com sessão iniciada já não existe.",
  "The submoment code is required.": "O código do submomento é obrigatório.",
  "The submoment name and code are required.": "O nome e o código do submomento são obrigatórios.",
  "The submoment name is required.": "O nome do submomento é obrigatório.",
  "The submoment position is invalid.": "A posição do submomento é inválida.",
  "The video has ended": "O vídeo terminou",
  "The video opened, but it may need to be selected again for local clip export.": "O vídeo foi aberto, mas poderá ter de ser selecionado novamente para exportar clips localmente.",
  "The video will be stored privately in Cloudflare R2 and will be available on every device signed into this account.": "O vídeo será guardado de forma privada na Cloudflare R2 e ficará disponível em todos os dispositivos com sessão iniciada nesta conta.",
  "There are no moments of this type.": "Não existem momentos deste tipo.",
  "There are no records yet.": "Ainda não existem registos.",
  "There are no submoments in this clip yet.": "Ainda não existem submomentos neste clip.",
  "There are no submoments in this moment yet.": "Ainda não existem submomentos neste momento.",
  "This browser does not support MP4/H.264 export. Use a recent version of Chrome or Edge.": "Este navegador não suporta exportação MP4/H.264. Utilize uma versão recente do Chrome ou Edge.",
  "This browser does not support video export.": "Este navegador não suporta exportação de vídeo.",
  "This full match video is not available.": "O vídeo completo deste jogo não está disponível.",
  "This linking code is invalid, expired or has already been used.": "Este código de ligação é inválido, expirou ou já foi utilizado.",
  "This linking code is no longer available.": "Este código de ligação já não está disponível.",
  "This match already has saved moments. Choose where to position the video.": "Este jogo já tem momentos guardados. Escolha onde pretende posicionar o vídeo.",
  "This match must be available in the cloud before a link can be created.": "O jogo tem de estar disponível na cloud antes de ser possível criar uma ligação.",
  "This perspective is saved for Dashboard and Reports. Both perspectives share the same video and moments, so no cloud file is duplicated.": "Esta perspetiva é guardada no Painel e nos Relatórios. Ambas as perspetivas partilham o mesmo vídeo e momentos, pelo que nenhum ficheiro é duplicado na cloud.",
  "This video cannot be exported with the scoreboard in this browser.": "Este vídeo não pode ser exportado com o placar neste navegador.",
  "Time in seconds": "Tempo em segundos",
  "Timed out while reading the video metadata.": "Foi excedido o tempo limite ao ler os metadados do vídeo.",
  "Timed out while reading the video.": "Foi excedido o tempo limite ao ler o vídeo.",
  "Timeline": "Linha temporal",
  "Try again": "Tentar novamente",
  "Type": "Tipo",
  "Undo the latest score change": "Anular a última alteração do resultado",
  "Unlock": "Desbloquear",
  "Upload each match video once, keep it private in Cloudflare R2 and continue the analysis from any authorised device.": "Carregue cada vídeo uma única vez, mantenha-o privado na Cloudflare R2 e continue a análise em qualquer dispositivo autorizado.",
  "Upload the video for this match.": "Carregue o vídeo deste jogo.",
  "Use current": "Usar atual",
  "Use this side in the application that still needs access to the shared videos.": "Utilize este lado na aplicação que ainda precisa de acesso aos vídeos partilhados.",
  "Use this side in the application whose video library should be kept as the destination.": "Utilize este lado na aplicação cuja biblioteca de vídeos deve ser mantida como destino.",
  "Use Upload new to add the first video to this account.": "Utilize «Carregar novo» para adicionar o primeiro vídeo a esta conta.",
  "Use video": "Usar vídeo",
  "Use video time": "Usar tempo do vídeo",
  "Username": "Nome de utilizador",
  "Uses the original perspective in which the moments are stored.": "Utiliza a perspetiva original em que os momentos estão guardados.",
  "Valid until": "Válido até",
  "Video not found.": "Vídeo não encontrado.",
  "Video position": "Posição do vídeo",
  "WebCodecs finished without video data.": "O WebCodecs terminou sem dados de vídeo.",
  "WebCodecs is not available in this browser.": "O WebCodecs não está disponível neste navegador.",
  "Which team do you want to analyse first?": "Que equipa pretende analisar primeiro?",
  "Which team do you want to analyse?": "Que equipa pretende analisar?",
  "Offensive Set Pieces": "Bolas paradas ofensivas",
  "Defensive Set Pieces": "Bolas paradas defensivas",
  "Defensive Half Recovery": "Recuperação no meio-campo defensivo",
  "Attacking Half Recovery": "Recuperação no meio-campo ofensivo",
  "Corner": "Canto",
  "Throw-in": "Lançamento lateral",
  "Free Kick": "Livre",
  "Penalty": "Penálti",
});

Object.assign(portuguese, {
  "· Analysing:": "· A analisar:",
  "· continuous playback": "· reprodução contínua",
  "1H start": "Início 1P",
  "1H end": "Fim 1P",
  "2H start": "Início 2P",
  "2H end": "Fim 2P",
  "A decorrer": "Em curso",
  "Cancel video upload": "Cancelar carregamento do vídeo",
  "Cannot delete a type with associated moments.": "Não é possível eliminar um tipo com momentos associados.",
  "Cannot delete a type with associated submoments.": "Não é possível eliminar um tipo com submomentos associados.",
  "Clip": "Clip",
  "Delete clip": "Eliminar clip",
  "Delete match": "Eliminar jogo",
  "Delete moment": "Eliminar momento",
  "Delete submoment": "Eliminar submomento",
  "Delete the last recorded moment": "Eliminar o último momento registado",
  "Delete this submoment?": "Eliminar este submomento?",
  "Delete type": "Eliminar tipo",
  "Don't have an account?": "Ainda não tem uma conta?",
  "Drag to change clip position": "Arraste para alterar a posição do clip",
  "Drag to reorder": "Arraste para reordenar",
  "Hide clip export options": "Ocultar opções de exportação do clip",
  "In the application that already has the videos, create and copy a code.": "Na aplicação que já contém os vídeos, crie e copie um código.",
  "moment": "momento",
  "moments": "momentos",
  "No matches found for “": "Não foram encontrados jogos para «",
  "Saved submoments": "Submomentos guardados",
  "Security": "Segurança",
  "submoments": "submomentos",
  "The submoment will be saved at": "O submomento será guardado em",
  "in the video": "no vídeo",
  "analyses selected": "análises selecionadas",
  "clips selected for export ·": "clips selecionados para exportação ·",
  "pontos": "pontos",
  "sub.": "sub.",
  "vs": "vs.",
  "No submoment": "Sem submomento",
  "A record with this name already exists.": "Já existe um registo com este nome.",
  "All of this type (": "Todos deste tipo (",
  "Checking whether the clip can be copied without re-encoding...": "A verificar se o clip pode ser copiado sem recodificação...",
  "Copying the original video data without quality loss...": "A copiar os dados originais do vídeo sem perda de qualidade...",
  "Could not save all videos. Check the available browser storage.": "Não foi possível guardar todos os vídeos. Verifique o espaço disponível no navegador.",
  "Encoding an exact cut with WebCodecs...": "A codificar um corte exato com WebCodecs...",
  "English": "Inglês",
  "Full match downloads are only available in Reports.": "As descargas de jogos completos só estão disponíveis nos Relatórios.",
  "Invalid cloud library linking action.": "Ação de ligação à biblioteca cloud inválida.",
  "Invalid match.": "Jogo inválido.",
  "Invalid multipart upload request.": "Pedido de carregamento multipartes inválido.",
  "Invalid resource.": "Recurso inválido.",
  "Invalid season or clubs.": "Época ou clubes inválidos.",
  "Invalid session.": "Sessão inválida.",
  "Invalid username or password.": "Nome de utilizador ou palavra-passe inválidos.",
  "Invalid video access area.": "Área de acesso ao vídeo inválida.",
  "Invalid video duration.": "Duração do vídeo inválida.",
  "Invalid video modification date.": "Data de modificação do vídeo inválida.",
  "Invalid video size.": "Tamanho do vídeo inválido.",
  "Name is required.": "O nome é obrigatório.",
  "of": "de",
  "Play all (": "Reproduzir todos (",
  "points": "pontos",
  "Preparing video...": "A preparar o vídeo...",
  "Record not found.": "Registo não encontrado.",
  "Score change is required.": "É obrigatória uma alteração do resultado.",
  "Select a video from the cloud library.": "Selecione um vídeo da biblioteca cloud.",
  "That cloud video is not available for this account.": "Esse vídeo da cloud não está disponível para esta conta.",
  "The account could not be created. Please try again.": "Não foi possível criar a conta. Tente novamente.",
  "The current password is incorrect.": "A palavra-passe atual está incorreta.",
  "The exact exporter stopped responding. Retrying with software encoding...": "O exportador exato deixou de responder. A tentar novamente com codificação por software...",
  "The multipart upload is no longer active.": "O carregamento multipartes já não está ativo.",
  "The shared cloud video is no longer available.": "O vídeo partilhado na cloud já não está disponível.",
  "The shared multipart upload is no longer active.": "O carregamento multipartes partilhado já não está ativo.",
  "The uploaded video is missing one or more parts.": "Falta uma ou mais partes no vídeo carregado.",
  "The username can only contain letters, numbers, dots, underscores and hyphens.": "O nome de utilizador só pode conter letras, números, pontos, underscores e hífenes.",
  "The username must contain between 3 and 32 characters.": "O nome de utilizador deve ter entre 3 e 32 caracteres.",
  "The video has not been uploaded to Cloudflare R2 yet.": "O vídeo ainda não foi carregado para a Cloudflare R2.",
  "This match does not have a video.": "Este jogo não tem vídeo.",
  "This username is already in use.": "Este nome de utilizador já está a ser utilizado.",
  "Using browser compatibility mode...": "A utilizar o modo de compatibilidade do navegador...",
  "You must change your password before continuing.": "Tem de alterar a palavra-passe antes de continuar.",
  "Analysis": "Análise",
  "Cancel active tag": "Cancelar marcação ativa",
  "Checking the source video before preparing the ZIP...": "A verificar o vídeo original antes de preparar o ZIP...",
  "Cloud upload incomplete": "Carregamento para a cloud incompleto",
  "Competition": "Competição",
  "Competition not set": "Competição não definida",
  "Confirm new password": "Confirmar nova palavra-passe",
  "Could not change the clip position.": "Não foi possível alterar a posição do clip.",
  "Could not classify the moment.": "Não foi possível classificar o momento.",
  "Could not classify the submoment.": "Não foi possível classificar o submomento.",
  "Could not create a linking code.": "Não foi possível criar um código de ligação.",
  "Could not create the download link.": "Não foi possível criar a ligação de descarga.",
  "Could not delete the moment.": "Não foi possível eliminar o momento.",
  "Could not delete the record.": "Não foi possível eliminar o registo.",
  "Could not delete the submoment type.": "Não foi possível eliminar o tipo de submomento.",
  "Could not export all moments.": "Não foi possível exportar todos os momentos.",
  "Could not export the report.": "Não foi possível exportar o relatório.",
  "Could not export the video.": "Não foi possível exportar o vídeo.",
  "Could not export the videos.": "Não foi possível exportar os vídeos.",
  "Could not link the cloud library.": "Não foi possível ligar a biblioteca cloud.",
  "Could not load the cloud library.": "Não foi possível carregar a biblioteca cloud.",
  "Could not open settings.": "Não foi possível abrir as definições.",
  "Could not open the destination folder.": "Não foi possível abrir a pasta de destino.",
  "Could not open this analysis.": "Não foi possível abrir esta análise.",
  "Could not prepare the videos for export.": "Não foi possível preparar os vídeos para exportação.",
  "Could not reorder the submoments.": "Não foi possível reordenar os submomentos.",
  "Could not save the analysis perspective.": "Não foi possível guardar a perspetiva da análise.",
  "Could not save the record.": "Não foi possível guardar o registo.",
  "Could not save the score.": "Não foi possível guardar o resultado.",
  "Could not save the submoment type.": "Não foi possível guardar o tipo de submomento.",
  "Could not save the submoment.": "Não foi possível guardar o submomento.",
  "Could not undo the score change.": "Não foi possível anular a alteração do resultado.",
  "Could not unlock settings.": "Não foi possível desbloquear as definições.",
  "Could not update the moment.": "Não foi possível atualizar o momento.",
  "Could not update the submoment.": "Não foi possível atualizar o submomento.",
  "Could not use this cloud video.": "Não foi possível utilizar este vídeo da cloud.",
  "Date not set": "Data não definida",
  "Direct cuts keep the source; exact fallback uses 18 Mbps": "Os cortes diretos preservam o original; o modo exato alternativo utiliza 18 Mbps",
  "Direct cuts keep the source; exact fallback uses 30 Mbps": "Os cortes diretos preservam o original; o modo exato alternativo utiliza 30 Mbps",
  "Direct cuts keep the source; exact fallback uses 9 Mbps": "Os cortes diretos preservam o original; o modo exato alternativo utiliza 9 Mbps",
  "Enter the global password to manage access passwords.": "Introduza a palavra-passe global para gerir as palavras-passe de acesso.",
  "Enter the password for this area to continue.": "Introduza a palavra-passe desta área para continuar.",
  "Error communicating with the app.": "Erro ao comunicar com a aplicação.",
  "Error saving match.": "Erro ao guardar o jogo.",
  "Exporting clips...": "A exportar clips...",
  "Finalizing exported files...": "A finalizar os ficheiros exportados...",
  "Finalizing the video in Cloudflare R2…": "A finalizar o vídeo na Cloudflare R2…",
  "Linking code copied.": "Código de ligação copiado.",
  "Moment type created.": "Tipo de momento criado.",
  "Moment type deleted.": "Tipo de momento eliminado.",
  "Moment type saved.": "Tipo de momento guardado.",
  "No cloud video uploaded yet": "Ainda não foi carregado nenhum vídeo para a cloud",
  "No date": "Sem data",
  "No marker": "Sem marcação",
  "No note": "Sem nota",
  "No season": "Sem época",
  "No short name": "Sem nome curto",
  "No time": "Sem tempo",
  "Opponent Analysis": "Análise do Adversário",
  "Play/Pause": "Reproduzir/Pausa",
  "Player Analysis": "Análise de Jogador",
  "Preparing multipart upload…": "A preparar o carregamento multipartes…",
  "Preparing the ZIP file...": "A preparar o ficheiro ZIP...",
  "Preparing the ZIP...": "A preparar o ZIP...",
  "Round": "Jornada",
  "Save edit": "Guardar edição",
  "Starting export...": "A iniciar a exportação...",
  "Submoment type created.": "Tipo de submomento criado.",
  "Submoment type deleted.": "Tipo de submomento eliminado.",
  "Submoment type saved.": "Tipo de submomento guardado.",
  "Team Analysis": "Análise de Equipa",
  "Temporary password": "Palavra-passe temporária",
  "The account could not be created.": "Não foi possível criar a conta.",
  "The full match video could not be exported.": "Não foi possível exportar o vídeo completo do jogo.",
  "The password could not be changed.": "Não foi possível alterar a palavra-passe.",
  "The password must contain at least 8 characters, including uppercase, lowercase and a number.": "A palavra-passe deve ter pelo menos 8 caracteres, incluindo uma maiúscula, uma minúscula e um número.",
  "The shared cloud library is now linked permanently.": "A biblioteca cloud partilhada ficou ligada permanentemente.",
  "The software WebCodecs retry was not possible. Trying compatibility mode.": "Não foi possível repetir com WebCodecs por software. A tentar o modo de compatibilidade.",
  "The upload was cancelled.": "O carregamento foi cancelado.",
  "The upload was interrupted.": "O carregamento foi interrompido.",
  "The video could not be uploaded.": "Não foi possível carregar o vídeo.",
  "This area could not be unlocked.": "Não foi possível desbloquear esta área.",
  "Unexpected error.": "Erro inesperado.",
  "Unnamed": "Sem nome",
  "Venue": "Local",
  "Video stored securely in Cloudflare R2.": "Vídeo guardado com segurança na Cloudflare R2.",
  "Video upload resumed and completed successfully.": "O carregamento do vídeo foi retomado e concluído com sucesso.",
  "WebCodecs export was not possible. Trying compatibility mode.": "Não foi possível exportar com WebCodecs. A tentar o modo de compatibilidade.",
  "WebCodecs stopped making progress.": "O WebCodecs deixou de avançar.",
  "With video": "Com vídeo",
  "Writing the report index...": "A criar o índice do relatório...",
  "Direct video export was not possible. Trying WebCodecs.": "Não foi possível exportar diretamente o vídeo. A tentar com WebCodecs.",
  "Replace": "Substituir",
  "with current time": "pelo tempo atual",
  "to current time": "para o tempo atual",
  "save current time": "guardar o tempo atual",
  "go to": "ir para",
  "clubs": "clubes",
  "Saving submoment copy": "A guardar cópia do submomento",
  "AP - Opponent Video Analysis": "AP - Análise de Vídeo do Adversário",
  "PWA for tactical football analysis with local video.": "PWA para análise tática de futebol com vídeo local.",
});

export function translateText(value: string, locale: Locale) {
  if (locale === "en") return value;
  const leading = value.match(/^\s*/)?.[0] || ""; const trailing = value.match(/\s*$/)?.[0] || ""; const core = value.trim();
  if (!core) return value;
  const exact = portuguese[core];
  if (exact) return `${leading}${exact}${trailing}`;
  const replacements: Array<[RegExp, string]> = [
    [/^(\d+) clips found$/, "$1 clips encontrados"],
    [/^(\d+) clips selected for export$/, "$1 clips selecionados para exportação"],
    [/^(\d+) clips selected for export · (\d+) analyses selected$/, "$1 clips selecionados para exportação · $2 análises selecionadas"],
    [/^Clip (\d+) of (\d+)$/, "Clip $1 de $2"],
    [/^Analysing: (.+)$/, "A analisar: $1"],
    [/^Analysing (.+)$/, "A analisar $1"],
    [/^(.+) · Analysing: (.+)$/, "$1 · A analisar: $2"],
    [/^(\d+) moments$/, "$1 momentos"],
    [/^(\d+) moment$/, "$1 momento"],
    [/^(\d+) in the video$/, "$1 no vídeo"],
    [/^(\d+) submoments$/, "$1 submomentos"],
    [/^(\d+) points$/, "$1 pontos"],
    [/^Export clips \((\d+)\)$/, "Exportar clips ($1)"],
    [/^Play all \((\d+)\)$/, "Reproduzir todos ($1)"],
    [/^Clips \((\d+)\)$/, "Clips ($1)"],
    [/^All of this type \((\d+)\)$/, "Todos deste tipo ($1)"],
    [/^No matches found for “(.+)”\.$/, "Não foram encontrados jogos para «$1»."],
    [/^Save (.+)$/, "Guardar $1"],
    [/^Delete type (.+)\?$/, "Eliminar o tipo $1?"],
    [/^Delete submoment type (.+)\?$/, "Eliminar o tipo de submomento $1?"],
    [/^Delete submoment (.+)\?$/, "Eliminar o submomento $1?"],
    [/^Delete this moment and its (\d+) submoments?\?$/, "Eliminar este momento e os seus $1 submomentos?"],
    [/^Delete (.+) from “(.+)” and its (\d+) submoments?\?$/, "Eliminar $1 de «$2» e os seus $3 submomentos?"],
    [/^The video for “(.+)” is not available\. Upload it from the analysis page first\.$/, "O vídeo de «$1» não está disponível. Carregue-o primeiro na página de análise."],
    [/^(.+) selected from the shared cloud library\.$/, "$1 selecionado na biblioteca cloud partilhada."],
    [/^Cancel upload \((\d+)%\)$/, "Cancelar carregamento ($1%)"],
    [/^Cancel (\d+)%$/, "Cancelar $1%"],
    [/^Uploading part (\d+) of (\d+)…$/, "A carregar parte $1 de $2…"],
    [/^Uploading (\d+) parts…$/, "A carregar $1 partes…"],
    [/^Uploaded (\d+) of (\d+) parts\.$/, "$1 de $2 partes carregadas."],
    [/^Resuming after (\d+) completed parts…$/, "A retomar após $1 partes concluídas…"],
    [/^(\d+) videos? (?:is|are) still missing\. You can add them individually\.$/, "Ainda faltam $1 vídeos. Pode adicioná-los individualmente."],
    [/^Choose a time between (.+) and (.+)\.$/, "Escolha um tempo entre $1 e $2."],
    [/^Download link copied\. It remains valid until (.+)\.$/, "Ligação de descarga copiada. É válida até $1."],
    [/^Full match exported with scoreboard and sound\.$/, "Jogo completo exportado com placar e som."],
    [/^Full match exported with scoreboard without sound\.$/, "Jogo completo exportado com placar e sem som."],
    [/^(\d+) clips exported successfully\.$/, "$1 clips exportados com sucesso."],
    [/^Export complete\. Missing videos: (.+)\.$/, "Exportação concluída. Vídeos em falta: $1."],
    [/^Destination selected: (.+)\. Checking the source video\.\.\.$/, "Destino selecionado: $1. A verificar o vídeo original..."],
    [/^Preparing (.+)…$/, "A preparar $1…"],
    [/^Exporting (\d+) of (\d+): (.+)$/, "A exportar $1 de $2: $3"],
    [/^(\d+) of (\d+): saving submoment copy (\d+) of (\d+)$/, "$1 de $2: a guardar a cópia do submomento $3 de $4"],
    [/^(\d+) of (\d+): (.+)$/, "$1 de $2: $3"],
    [/^Direct cut: (\d+)%$/, "Corte direto: $1%"],
    [/^Exact cut with WebCodecs: (\d+)%$/, "Corte exato com WebCodecs: $1%"],
    [/^Exporting full match: (\d+)%$/, "A exportar jogo completo: $1%"],
    [/^(.+) saved: (.+) - (.+)$/, "$1 guardado: $2 - $3"],
    [/^Delete (.+) at (.+)\?$/, "Eliminar $1 em $2?"],
    [/^(.+) started at (.+)\.$/, "$1 iniciado em $2."],
    [/^(.+): mark the zone on the field\.$/, "$1: marque a zona no campo."],
    [/^(.+) logged at (.+)\.$/, "$1 registado em $2."],
    [/^Match period time saved at (.+)\.$/, "Tempo do período de jogo guardado em $1."],
    [/^MP4 video exported \(direct cut, no quality loss\): (.+)$/, "Vídeo MP4 exportado (corte direto, sem perda de qualidade): $1"],
    [/^MP4 video exported \(exact WebCodecs cut\): (.+)$/, "Vídeo MP4 exportado (corte exato com WebCodecs): $1"],
    [/^MP4 video exported \(compatibility mode\): (.+)$/, "Vídeo MP4 exportado (modo de compatibilidade): $1"],
    [/^MP4 video exported \((.+)\): (.+)$/, "Vídeo MP4 exportado ($1): $2"],
    [/^(\d+) MP4 videos exported to the selected folder\.$/, "$1 vídeos MP4 exportados para a pasta selecionada."],
    [/^(\d+) MP4 videos exported(.*)\.$/, "$1 vídeos MP4 exportados$2."],
    [/^(\d+) moments exported successfully to the selected folder\.$/, "$1 momentos exportados com sucesso para a pasta selecionada."],
    [/^(\d+) moments exported successfully(.*)\.$/, "$1 momentos exportados com sucesso$2."],
    [/^(.+): save current time$/, "$1: guardar o tempo atual"],
    [/^(.+): go to (.+)$/, "$1: ir para $2"],
    [/^Replace (.+) with current time$/, "Substituir $1 pelo tempo atual"],
    [/^Replace (.+)$/, "Substituir $1"],
    [/^Set (.+) to current time$/, "Definir $1 para o tempo atual"],
    [/^Delete "(.+)", all saved perspectives and all associated moments\?$/, "Eliminar «$1», todas as perspetivas guardadas e todos os momentos associados?"],
    [/^Delete “(.+)”\?$/, "Eliminar «$1»?"],
    [/^(.+) · (\d+) clubs$/, "$1 · $2 clubes"],
    [/^Unlock (.+)$/, "Desbloquear $1"],
    [/^Enter the (.+) password, or the global password to unlock everything\.$/, "Introduza a palavra-passe de $1 ou a palavra-passe global para desbloquear tudo."],
    [/^(.+) password changed\.$/, "Palavra-passe de $1 alterada."],
    [/^Round (\d+) - (.+) vs (.+)$/, "Jornada $1 - $2 vs. $3"],
    [/^Round (\d+)$/, "Jornada $1"],
    [/^“(.+)” does not match the expected video for “(.+)” \((.+)\)\.$/, "«$1» não corresponde ao vídeo esperado para «$2» ($3)."],
    [/^Drag clip (\d+) to change its position$/, "Arraste o clip $1 para alterar a sua posição"],
    [/^Edit (.+)$/, "Editar $1"],
    [/^Delete (.+)$/, "Eliminar $1"],
    [/^Missing (.+)\. Configure the shared Cloudflare R2 credentials\.$/, "$1 em falta. Configure as credenciais partilhadas da Cloudflare R2."],
    [/^Missing (.+)\. Configure the Cloudflare R2 credentials\.$/, "$1 em falta. Configure as credenciais da Cloudflare R2."],
    [/^Shared Cloudflare R2 returned (.+): (.+)$/, "A Cloudflare R2 partilhada devolveu $1: $2"],
    [/^Cloudflare R2 returned (.+): (.+)$/, "A Cloudflare R2 devolveu $1: $2"],
    [/^(.+) Select the same file again to resume it\.$/, "$1 Selecione novamente o mesmo ficheiro para retomar."],
    [/^Cloudflare rejected a video part \((\d+)\)\.$/, "A Cloudflare rejeitou uma parte do vídeo ($1)."],
    [/^WebCodecs cannot export this video(.*)\.$/, "O WebCodecs não consegue exportar este vídeo$1."],
    [/^Exporting (\d+) \/ (\d+)\.\.\.$/, "A exportar $1 / $2..."],
  ];
  for (const [pattern, replacement] of replacements) if (pattern.test(core)) return `${leading}${core.replace(pattern, replacement)}${trailing}`;
  return value;
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>("en");
  useEffect(() => { const saved = window.localStorage.getItem(storageKey); setLocaleState(saved === "pt" ? "pt" : "en"); }, []);
  function setLocale(next: Locale) { setLocaleState(next); window.localStorage.setItem(storageKey, next); document.documentElement.lang = next === "pt" ? "pt-PT" : "en"; }
  useEffect(() => { document.documentElement.lang = locale === "pt" ? "pt-PT" : "en"; }, [locale]);
  useEffect(() => {
    const nativeAlert = window.alert.bind(window);
    const nativeConfirm = window.confirm.bind(window);
    const nativePrompt = window.prompt.bind(window);
    const translatedAlert = (message?: unknown) => nativeAlert(translateText(String(message ?? ""), locale));
    const translatedConfirm = (message?: string) => nativeConfirm(translateText(String(message ?? ""), locale));
    const translatedPrompt = (message?: string, defaultValue?: string) => nativePrompt(translateText(String(message ?? ""), locale), defaultValue);
    window.alert = translatedAlert;
    window.confirm = translatedConfirm;
    window.prompt = translatedPrompt;
    return () => {
      if (window.alert === translatedAlert) window.alert = nativeAlert;
      if (window.confirm === translatedConfirm) window.confirm = nativeConfirm;
      if (window.prompt === translatedPrompt) window.prompt = nativePrompt;
    };
  }, [locale]);
  useEffect(() => {
    const localizeTree = (root: Node) => {
      if (root instanceof Text) localizeTextNode(root, locale);
      if (root instanceof Element) localizeAttributes(root, locale);
      const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT | NodeFilter.SHOW_ELEMENT);
      let node: Node | null = walker.nextNode();
      while (node) { if (node instanceof Text) localizeTextNode(node, locale); else if (node instanceof Element) localizeAttributes(node, locale); node = walker.nextNode(); }
    };
    localizeTree(document.documentElement);
    const observer = new MutationObserver((mutations) => {
      for (const mutation of mutations) {
        if (mutation.type === "characterData") localizeTree(mutation.target);
        if (mutation.type === "attributes" && mutation.target instanceof Element) localizeAttributes(mutation.target, locale);
        mutation.addedNodes.forEach(localizeTree);
      }
    });
    observer.observe(document.documentElement, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: ["title", "aria-label", "placeholder", "content"] });
    return () => observer.disconnect();
  }, [locale]);
  const value = useMemo(() => ({ locale, setLocale, t: (english: string) => translateText(english, locale) }), [locale]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

function localizeTextNode(node: Text, locale: Locale) {
  if (node.parentElement?.closest("script,style")) return;
  const current = node.data;
  const saved = textOrigins.get(node);
  if (locale === "en") {
    if (saved && current === saved.pt) node.data = saved.en;
    return;
  }
  if (saved && current === saved.pt) return;
  const translated = translateText(current, "pt");
  textOrigins.set(node, { en: current, pt: translated });
  if (translated !== current) node.data = translated;
}

function localizeAttributes(element: Element, locale: Locale) {
  for (const name of ["title", "aria-label", "placeholder", "content"]) {
    const current = element.getAttribute(name); if (!current) continue;
    let records = attributeOrigins.get(element); if (!records) { records = new Map(); attributeOrigins.set(element, records); }
    const saved = records.get(name);
    if (locale === "en") { if (saved && current === saved.pt) element.setAttribute(name, saved.en); continue; }
    if (saved && current === saved.pt) continue;
    const translated = translateText(current, "pt"); records.set(name, { en: current, pt: translated });
    if (translated !== current) element.setAttribute(name, translated);
  }
}

export function useLanguage() { return useContext(LanguageContext); }

export function LanguageSwitcher() {
  const { locale, setLocale } = useLanguage();
  return <div className="flex items-center overflow-hidden rounded-md border border-white/10 bg-white/[.03] p-0.5" aria-label="Language">
    <button type="button" onClick={() => setLocale("pt")} className={`h-7 rounded px-2 text-[11px] transition ${locale === "pt" ? "bg-cyan-300 text-slate-950" : "text-slate-400 hover:text-white"}`} title="Português">🇵🇹 <span className="hidden lg:inline">PT</span></button>
    <button type="button" onClick={() => setLocale("en")} className={`h-7 rounded px-2 text-[11px] transition ${locale === "en" ? "bg-cyan-300 text-slate-950" : "text-slate-400 hover:text-white"}`} title="English">🇬🇧 <span className="hidden lg:inline">EN</span></button>
  </div>;
}
