"use client";

import { FormEvent, useEffect, useState } from "react";
import { KeyRound, Loader2, ShieldCheck } from "lucide-react";
import { Button, FieldLabel, Panel, TextInput } from "@/components/ui";
import { accessAreaDetails, accessAreas, type AccessArea } from "@/lib/access-areas";
import { apiFetch } from "@/lib/http";

export function ManagementPasswordPanel() {
  const [globalUnlocked, setGlobalUnlocked] = useState<boolean | null>(null);
  const [busy, setBusy] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  useEffect(() => { apiFetch<{ accessControl: { globalUnlocked: boolean } }>("/api/account").then((account) => setGlobalUnlocked(account.accessControl.globalUnlocked)).catch((error: Error) => { setGlobalUnlocked(false); setMessage(error.message); }); }, []);
  async function unlock(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; setBusy("unlock"); setMessage(null); try { await apiFetch("/api/access-control", { method: "POST", body: JSON.stringify({ action: "unlockGlobal", password: new FormData(form).get("password") }) }); form.reset(); window.location.reload(); } catch (error) { setMessage(error instanceof Error ? error.message : "Could not unlock settings."); } finally { setBusy(null); } }
  async function change(event: FormEvent<HTMLFormElement>, target: AccessArea | "global") { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); const password = String(data.get("password") || ""); if (password !== String(data.get("confirmation") || "")) return setMessage("The new passwords do not match."); setBusy(target); setMessage(null); try { await apiFetch("/api/access-control", { method: "PATCH", body: JSON.stringify({ target, password }) }); form.reset(); setMessage(`${target === "global" ? "Global" : accessAreaDetails[target].label} password changed.`); } catch (error) { setMessage(error instanceof Error ? error.message : "The password could not be changed."); } finally { setBusy(null); } }
  return <Panel className="p-4"><div className="flex gap-3"><ShieldCheck className="text-violet-200"/><div><FieldLabel>Security</FieldLabel><h2 className="mt-1 font-semibold text-white">Area and global passwords</h2><p className="mt-1 text-xs text-slate-400">Each area has its own password. The global password unlocks the entire application.</p></div></div>{message ? <p className="mt-3 rounded-md border border-white/10 px-3 py-2 text-xs text-slate-300">{message}</p> : null}{globalUnlocked === null ? <p className="mt-4 text-xs text-slate-400"><Loader2 className="mr-2 inline animate-spin" size={14}/>Checking access...</p> : !globalUnlocked ? <form className="mt-4 flex gap-2" onSubmit={(event) => void unlock(event)}><TextInput name="password" type="password" placeholder="Global password" required/><Button variant="primary" disabled={busy === "unlock"}><KeyRound size={14}/>Unlock</Button></form> : <div className="mt-4 grid gap-3 lg:grid-cols-2">{[...accessAreas, "global" as const].map((target) => <form key={target} className="rounded-lg border border-white/10 bg-black/10 p-3" onSubmit={(event) => void change(event, target)}><FieldLabel>{target === "global" ? "Global" : accessAreaDetails[target].label}</FieldLabel><div className="mt-2 grid gap-2 sm:grid-cols-[1fr_1fr_auto]"><TextInput name="password" type="password" placeholder="New password" minLength={4} required/><TextInput name="confirmation" type="password" placeholder="Confirm" minLength={4} required/><Button size="sm" disabled={busy === target}>{busy === target ? <Loader2 size={13} className="animate-spin"/> : "Change"}</Button></div></form>)}</div>}</Panel>;
}
